### ISSUE TITLE
How easy is it to fix a car?

### ISSUE THREAD

**Issue by ijosbuttler** [shohan-pherones/torque-xtreme#1]
Even if you aren't an expert on cars, you can accomplish most basic maintenance and [repair work](https://alzaabiautocare.com/) on your own. Replace a worn distributor cap, for instance, to maintain the car's electrical power. With a few basic tools, the fuel filter and air filter are also easy to swap out to ensure your car continues to run well.

**Comment by jordanhandrei** [comment]
이스포츠 대회중 최대 규모의 대회이자 리그 오브 레전드 [롤배팅](https://esports-ocean.com/) 월드 챔피언십을 줄여서 롤드컵 이라 통칭하고 있습니다.
매년 하반기에 대회를 개최하고 한해를 마무리 하는 이스포츠에서 가장큰 대회입니다.
세계적으로 엄청나게 인기가 있으며, 리그오브레전드 프로게이머 들에게서도 가장 큰 꿈의 무대같은 대회입니다.
동시 시청자 또한 매대회 마다 신기록을 세우고 있습니다. 리그 오브 레전드 는 라이엇 이 개발한 pc게임으로 5명의 챔피언으로
상대방의 넥서스를 파괴하거나 먼저 서렌을 받아야 나는 게임으로 세계적으로 인기가 있는 전략시뮬레이션 게임중에 하나로
손꼽히고 있습니다. 10년이 지난 지금도 전세계 적으로 매우인기가 있으며 LCK, LCS, LEC, LPL 등 지역별
나라의 국내 대회 로 통칭되는 대회또한 인기가 많은걸로 확인이 됩니다. 롤드컵 우승시 우승팀에 대한 스킨이 발매가 되고
우승상금또한 30억가량 추정되고 있습니다. 그리고 라이엇게임즈에 우승한팀의 선수의 이름이 기록되고 있습니다.
이러한 부분이 리그오브 레전드 프로게임머 들에게 매우 상징적으로 느껴질것 같습니다.
